# Site settings
author: Haley Grassi
title: The World of Software Engineering
header-img: img/home-bg.png
email: teacherhaleymarie@gmail.com
copyright_name: Haley Grassi
description: > # this means to ignore newlines until "baseurl:"
  A blog about what a new software engineer learns. 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Halezmarie

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
